### ISSUE TITLE
Trainer Studio crashes when opened from Windows search results

### ISSUE THREAD

**Issue by Andrej123456789** [EndermanPC/TS-Source#2]
**Describe the bug**
Trainer Studio crashes when it's opened from Windows search, but when it's opened directly from executable in installed folder, it works normally.

**To Reproduce**
1. Search for `Trainer Studio`
2. Open it (crashes)
3. Find location where Trainer Studio is installed
4. Run Trainer Studio from there (works)

**Expected behavior**
App works when opened through Windows Search

**Screenshots**
Check first video.

**System (please complete the following information):**
 - OS: Windows 11
 - Build type: Release
 - Build: 23H2 (OS Build 22631.4460)

**Additional context**
Windows Search guides to correct executable path (check second video).

https://github.com/user-attachments/assets/7b27410c-427e-43ec-a31d-81f95c672895

https://github.com/user-attachments/assets/f361f8da-84e5-4ec4-a224-27daf437580f

**Comment by EndermanPC** [comment]
Thanks for reporting the issue, I will try to fix it as soon as possible.

**Comment by Andrej123456789** [comment]
Thank you for fixing the issue!
